name: integration

env:
  DENO_VERSION: 1.x

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**/*.ts'
      - '.github/workflows/integration.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.ts'
      - '.github/workflows/integration.yml'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: Check
        run: deno task check

  test:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          path: "./repo"

      - name: Checkout denops.vim
        uses: actions/checkout@v4
        with:
          repository: "vim-denops/denops.vim"
          path: "./denops.vim"

      - name: Setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: Setup Vim
        uses: rhysd/action-setup-vim@v1

      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true

      - name: Test
        run: deno task test
        env:
          DENOPS_TEST_DENOPS_PATH: "../denops.vim"
        working-directory: ./repo
